---
title: Fart Detector
hero_image: images/banner.png
description: Make an alarm that's triggered by certain potent gases
original_url: https://raspberrypi.org/learning/fart-detector
theme: green
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-3, manufacture-0, community-0
interests: humour
technologies: raspberry-pi, electronic-components, python
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: 'Giving your Pi a ''nose'': how it works'
- title: Wire up the air quality sensor
- title: Wire up the trigger pin
- title: Build a resistor ladder DAC
- title: Play a test alarm sound
- title: Write code to calibrate the ladder DAC
- title: Monitoring for farts and raising the alarm
- title: Continuous monitoring and recalibration
- title: Customise the output
  completion: internal
- title: Troubleshooting
