---
title: Fart Detector
hero_image: images/banner.png
description: Make an alarm that's triggered by certain potent gases
original_url: https://raspberrypi.org/learning/fart-detector
theme: blue
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Fart Detector
- title: 'Giving your Pi a ''nose'': how it works'
- title: Wire up the air quality sensor
- title: Wire up the trigger pin
- title: Build a resistor ladder DAC
- title: Play a test alarm sound
- title: Write code to calibrate the ladder DAC
- title: Monitoring for farts and raising the alarm
- title: Continuous monitoring and recalibration
- title: Customise the output
- title: Troubleshooting

